WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Initialized distributed mode...
Start training
start creating model... (in yaml_config.py)
Traceback (most recent call last):
  File "/home/hslee/Desktop/RT-DETR-ADN/06_RT-DETR-ADN/tools/train.py", line 63, in <module>
    main(args)
  File "/home/hslee/Desktop/RT-DETR-ADN/06_RT-DETR-ADN/tools/train.py", line 49, in main
    solver.fit() # training
    ^^^^^^^^^^^^
  File "/home/hslee/Desktop/RT-DETR-ADN/06_RT-DETR-ADN/tools/../src/solver/det_solver.py", line 23, in fit
    self.train()
  File "/home/hslee/Desktop/RT-DETR-ADN/06_RT-DETR-ADN/tools/../src/solver/solver.py", line 80, in train
    self.setup()
  File "/home/hslee/Desktop/RT-DETR-ADN/06_RT-DETR-ADN/tools/../src/solver/solver.py", line 33, in setup
    model = cfg.model.to(device) # cfg.model = (YAMLConfig Class).(method) in yaml_config.py
            ^^^^^^^^^
  File "/home/hslee/Desktop/RT-DETR-ADN/06_RT-DETR-ADN/tools/../src/core/yaml_config.py", line 56, in model
    self._model = create(self.yaml_cfg['model'])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hslee/Desktop/RT-DETR-ADN/06_RT-DETR-ADN/tools/../src/core/yaml_utils.py", line 129, in create
    cls_kwargs[k] = create(_cfg['_name'])
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hslee/Desktop/RT-DETR-ADN/06_RT-DETR-ADN/tools/../src/core/yaml_utils.py", line 154, in create
    return cls(**cls_kwargs)
           ^^^^^^^^^^^^^^^^^
  File "/home/hslee/Desktop/RT-DETR-ADN/06_RT-DETR-ADN/tools/../src/nn/backbone/resnet.py", line 190, in __init__
    self.layer1 = self._make_layer(block, 64, layers[0])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hslee/Desktop/RT-DETR-ADN/06_RT-DETR-ADN/tools/../src/nn/backbone/resnet.py", line 236, in _make_layer
    block(
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/home/hslee/Desktop/RT-DETR-ADN/06_RT-DETR-ADN/tools/train.py", line 63, in <module>
    main(args)
  File "/home/hslee/Desktop/RT-DETR-ADN/06_RT-DETR-ADN/tools/train.py", line 49, in main
    solver.fit() # training
    ^^^^^^^^^^^^
  File "/home/hslee/Desktop/RT-DETR-ADN/06_RT-DETR-ADN/tools/../src/solver/det_solver.py", line 23, in fit
    self.train()
  File "/home/hslee/Desktop/RT-DETR-ADN/06_RT-DETR-ADN/tools/../src/solver/solver.py", line 80, in train
    self.setup()
  File "/home/hslee/Desktop/RT-DETR-ADN/06_RT-DETR-ADN/tools/../src/solver/solver.py", line 33, in setup
    model = cfg.model.to(device) # cfg.model = (YAMLConfig Class).(method) in yaml_config.py
            ^^^^^^^^^
  File "/home/hslee/Desktop/RT-DETR-ADN/06_RT-DETR-ADN/tools/../src/core/yaml_config.py", line 56, in model
    self._model = create(self.yaml_cfg['model'])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hslee/Desktop/RT-DETR-ADN/06_RT-DETR-ADN/tools/../src/core/yaml_utils.py", line 129, in create
    cls_kwargs[k] = create(_cfg['_name'])
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hslee/Desktop/RT-DETR-ADN/06_RT-DETR-ADN/tools/../src/core/yaml_utils.py", line 154, in create
    return cls(**cls_kwargs)
           ^^^^^^^^^^^^^^^^^
  File "/home/hslee/Desktop/RT-DETR-ADN/06_RT-DETR-ADN/tools/../src/nn/backbone/resnet.py", line 190, in __init__
    self.layer1 = self._make_layer(block, 64, layers[0])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hslee/Desktop/RT-DETR-ADN/06_RT-DETR-ADN/tools/../src/nn/backbone/resnet.py", line 236, in _make_layer
    block(
TypeError: 'NoneType' object is not callable
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 829359) of binary: /home/hslee/anaconda3/bin/python
Traceback (most recent call last):
  File "/home/hslee/anaconda3/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/hslee/anaconda3/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/hslee/anaconda3/lib/python3.11/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/hslee/anaconda3/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/hslee/anaconda3/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hslee/anaconda3/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-06-09_14:53:43
  host      : ada
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 829360)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-06-09_14:53:43
  host      : ada
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 829359)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
